In [3]:

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV,KFold
from sklearn.preprocessing import LabelEncoder,StandardScaler
import seaborn as sns
import warnings
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
warnings.filterwarnings('ignore')
import plotly as px


In [4]:
df = pd.read_csv('audit_risk.csv')
df.head()

Sector_score LOCATION_ID  PARA_A  Score_A  Risk_A  PARA_B  Score_B  Risk_B  \
0          3.89          23    4.18      0.6   2.508    2.50      0.2   0.500   
1          3.89           6    0.00      0.2   0.000    4.83      0.2   0.966   
2          3.89           6    0.51      0.2   0.102    0.23      0.2   0.046   
3          3.89           6    0.00      0.2   0.000   10.80      0.6   6.480   
4          3.89           6    0.00      0.2   0.000    0.08      0.2   0.016   

   TOTAL  numbers  ...  RiSk_E  History  Prob  Risk_F  Score  Inherent_Risk  \
0   6.68      5.0  ...     0.4        0   0.2     0.0    2.4          8.574   
1   4.83      5.0  ...     0.4        0   0.2     0.0    2.0          2.554   
2   0.74      5.0  ...     0.4        0   0.2     0.0    2.0          1.548   
3  10.80      6.0  ...     0.4        0   0.2     0.0    4.4         17.530   
4   0.08      5.0  ...     0.4        0   0.2     0.0    2.0          1.416   

   CONTROL_RISK  Detection_Risk  Audit_Risk  Risk  
0           0.4             0.5      1.7148     1  
1           0.4             0.5      0.5108     0  
2           0.4             0.5      0.3096     0  
3           0.4             0.5      3.5060     1  
4           0.4             0.5      0.2832     0  

[5 rows x 27 columns]

In [5]:
df['Risk'].value_counts()

0    471
1    305
Name: Risk, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 776 entries, 0 to 775
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Sector_score    776 non-null    float64
 1   LOCATION_ID     776 non-null    object 
 2   PARA_A          776 non-null    float64
 3   Score_A         776 non-null    float64
 4   Risk_A          776 non-null    float64
 5   PARA_B          776 non-null    float64
 6   Score_B         776 non-null    float64
 7   Risk_B          776 non-null    float64
 8   TOTAL           776 non-null    float64
 9   numbers         776 non-null    float64
 10  Score_B.1       776 non-null    float64
 11  Risk_C          776 non-null    float64
 12  Money_Value     775 non-null    float64
 13  Score_MV        776 non-null    float64
 14  Risk_D          776 non-null    float64
 15  District_Loss   776 non-null    int64  
 16  PROB            776 non-null    float64
 17  RiSk_E          776 non-null    flo

In [7]:
#df = df.select_dtypes(exclude='objects')
df.drop(columns="LOCATION_ID",inplace=True)

In [8]:
df.dropna(inplace=True)

In [9]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state= 42)

In [11]:
print(type(y_train))

<class 'pandas.core.series.Series'>


In [12]:
y_train = y_train.values.reshape(-1,1)
y_test = y_test.values.reshape(-1,1)

In [13]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [14]:
y_pred = lr.predict(X_test)
y_pred

array([0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0], dtype=int64)

In [15]:
accuracy_score(y_test,y_pred)

0.9935483870967742

In [16]:
l = df.corr()["Risk"]
k = l[(l>0.38)&(l<0.6)]

In [17]:
k

Risk_A           0.384869
District_Loss    0.403591
RiSk_E           0.411594
CONTROL_RISK     0.416285
Name: Risk, dtype: float64

In [18]:
a = k.index.tolist()
a.append('Risk')
df_ll = df[a]

In [19]:
df_ll

Risk_A  District_Loss  RiSk_E  CONTROL_RISK  Risk
0     2.508              2     0.4           0.4     1
1     0.000              2     0.4           0.4     0
2     0.102              2     0.4           0.4     0
3     0.000              2     0.4           0.4     1
4     0.000              2     0.4           0.4     0
..      ...            ...     ...           ...   ...
771   0.098              2     0.4           0.4     0
772   0.094              2     0.4           0.4     0
773   0.048              2     0.4           0.4     0
774   0.040              2     0.4           0.4     0
775   0.000              2     0.4           0.4     0

[775 rows x 5 columns]

In [20]:
from sklearn.metrics import precision_score


X, y = df_ll.drop(columns="Risk"), df_ll["Risk"]

X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.3, random_state=42)

y_train  = y_train.values.reshape(-1,1)
y_test = y_test.values.reshape(-1,1)

lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
accuracy_score(y_test,y_pred)
precision_score(y_test,y_pred)

0.9295774647887324

In [21]:
def preprocess(df):
    
    df_n  = df.select_dtypes(exclude= 'object')
    
    df_n.dropna(inplace =True)
    X,y = df_n.drop(columns = 'Risk'),df['Risk']
    
    X_trian , X_test , y_train, y_test = train_test_split(X,y , test_size=0.3, random_state=42)
    
    y_train = y_train.values.reshape(-1,1)
    y_test = y_test.values.reshape(-1,1)
    return X_train,X_test,y_train,y_test    

In [22]:
def modeling(df):
    
    X_train, X_test, y_train, y_test = preprocess(df)
    lr = LogisticRegression()
    lr.fit(X_train,y_train)
    y_pred = lr.predict(X_test)
    return y_test,y_pred

In [23]:
y_test ,y_pred = modeling(df_ll)
accuracy_score(y_test,y_pred)


0.8626609442060086

In [24]:
folds = KFold(n_splits=5, shuffle = True, random_state = 42)
hyper_parameter = [{"penalty": ['l2','l1'],
                    "C": [0.01,0.1,1,10,100]}]

grid  = GridSearchCV(estimator=lr,
                     param_grid=hyper_parameter,
                     scoring='accuracy',
                     cv = folds)

In [25]:
grid.fit(X_train,y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=42, shuffle=True),
             estimator=LogisticRegression(),
             param_grid=[{'C': [0.01, 0.1, 1, 10, 100],
                          'penalty': ['l2', 'l1']}],
             scoring='accuracy')

In [26]:
y_pred = grid.predict(X_test)
y_pred

array([0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1], dtype=int64)

In [27]:
accuracy_score(y_test,y_pred)

0.8583690987124464

In [28]:
confusion_matrix(y_test,y_pred)

array([[135,   5],
       [ 28,  65]], dtype=int64)